apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
  labels:
    app: user-java
spec:
  selector:
    app: user-java
  type: ClusterIP
  ports:
    - name: user-java-http
      protocol: TCP
      port: 80
