apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
  labels:
    app: poi
spec:
  selector:
    app: poi
  type: ClusterIP
  ports:
    - name: poi-http
      protocol: TCP
      port: 80
