apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripviewer-ingress
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/azure-dns-label-name: tripsinsights.westus.cloudapp.azure.com
spec:
  ingressClassName: nginx
  rules:
    - host: tripsinsights.westus.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tripviewer-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/azure-dns-label-name: tripsinsights.westus.cloudapp.azure.com
spec:
  ingressClassName: nginx
  rules:
    - host: tripsinsights.westus.cloudapp.azure.com
      http:
        paths:
          - path: /api/poi
            pathType: Prefix
            backend:
              service:
                name: poi-service
                port:
                  number: 80
          - path: /api/trips
            pathType: Prefix
            backend:
              service:
                name: trips-service
                port:
                  number: 80
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: userprofile-service
                port:
                  number: 80
          - path: /api/user-java
            pathType: Prefix
            backend:
              service:
                name: user-java-service
                port:
                  number: 80
