apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trips
  name: trips
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trips
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trips
    spec:
      volumes:
        - name: db-user-pass-volume
          secret:
            secretName: db-user-pass
            optional: true
      containers:
        - image: registrynoo3886.azurecr.io/tripinsights/trips:1.0
          imagePullPolicy: IfNotPresent
          name: trips
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: db-user-pass-volume
              mountPath: "/secrets"
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
