apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  type: ClusterIP
  ports:
    - name: userprofile-http
      protocol: TCP
      port: 80
      targetPort: http
