apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tripviewer
  name: tripviewer
  namespace: web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripviewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: registrynoo3886.azurecr.io/tripinsights/tripviewer:1.0
        imagePullPolicy: IfNotPresent
        name: tripviewer
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile-service.api.svc.cluster.local:80"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-service.api.svc.cluster.local:80"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30